src/product_card/urls.py
from django.urls import path
from . import views

app_name = "product_card"
urlpatterns = [
    path('pc_preview/<int:pk>/', views.ShowProductCard.as_view(), name='pc_detail'),
    path('pc_create/', views.CreateProductCard.as_view(), name='pc_create'),
    path('pc_update/<int:pk>/', views.UpdateProductCard.as_view(), name='pc_update'),
    path('pc_delete/<int:pk>/', views.DeleteProductCard.as_view(), name='pc_delete'),
    path('pc_list/', views.ShowProductCardList.as_view(), name='pc_list'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('navigation/', views.PortalView.as_view(), name='service_navigation')
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from product_card.views import SearchResultView, CatalogView


urlpatterns = [
    path("admin/", admin.site.urls),
    path('references/', include('references.urls', namespace="references")),
    path('product_card/', include('product_card.urls', namespace="product_card")),
    path('search/', SearchResultView.as_view(), name='search_results'),
    path('', CatalogView.as_view(), name='catalog'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/references/urls.py
from django.urls import path
from . import views

app_name = "references"
urlpatterns = [

    #Authors URLs

    path('author_preview/<int:pk>/', views.ShowAuthor.as_view(), name='author_detail'),
    path('author_create/', views.CreateAuthor.as_view(), name='author_create'),
    path('author_update/<int:pk>/', views.UpdateAuthor.as_view(), name='author_update'),
    path('author_delete/<int:pk>/', views.DeleteAuthor.as_view(), name='author_delete'),
    path('authors_list/', views.ShowAuthors.as_view(), name='authors_list'),
]

src/product_card/models.py
from django.db import models
from references.models import BookAuthor
from django.urls import reverse_lazy
from django.utils.datetime_safe import date
from django.core.exceptions import ValidationError

# Create your models here.

class Book(models.Model):
    name = models.CharField(
       max_length=70,
       verbose_name="Book name"
    )
    image = models.ImageField(
        verbose_name="Book image",
        upload_to='uploads/%Y/%m/%d/',
        blank=True,
        null=True
    )
    author = models.ManyToManyField(
        BookAuthor,
    )
    publishing_year=models.CharField(
        max_length=11,
        verbose_name="Publishing year"
    )
    pages = models.IntegerField(
        verbose_name="Pages"
    )
    binding = models.CharField(
        max_length=15,
        verbose_name="Binding"
    )
    format = models.CharField(
        max_length=7,
        verbose_name="Format"
    )
    isbn = models.CharField(
        max_length=30,
        verbose_name="ISBN"
    )
    weight = models.IntegerField(
        verbose_name="Weight",
        help_text="Weight in grams"
    )
    age_restriction = models.IntegerField( 
        verbose_name="Age restriction"
    )
    date_of_addition = models.DateField(
        verbose_name="Date of addition"
    )
    modification_date = models.DateTimeField(
        auto_now=True,
        verbose_name="Modification date"
    )
    description = models.TextField(
        blank = True,
        null = True
    )
    

    def get_absolute_url(self):
        return reverse_lazy('product_card:pc_detail', kwargs={'pk': self.pk})

    def clean(self):
        if str(self.date_of_addition) > str(date.today()):
            raise ValidationError({'date_of_addition': 'Must not be later than today!'})

    def __str__(self):
        return str(self.name)

src/product_card/forms.py
from django import forms
from . import models


class DateInput(forms.DateInput):
    input_type = 'date'


class ProductCardForm(forms.ModelForm):
    class Meta:
        model = models.Book
        fields = ['name', 'image', 'author', 'publishing_year', 'pages', 'binding',\
         'format', 'isbn', 'weight', 'age_restriction','date_of_addition', 'description'
         ]
        widgets = {'date_of_addition' : DateInput()}

src/product_card/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.urls import reverse_lazy
from . import models, forms
from django.core.paginator import Paginator
from django.db.models import Q

# Create your views here.

class ShowProductCardList(generic.ListView):
    model = models.Book
    template_name = 'product_card/list_pc.html'


class ShowProductCard(generic.DetailView):
    model = models.Book
    template_name = 'product_card/detail_pc.html'


class CreateProductCard(generic.CreateView):
    model = models.Book
    form_class = forms.ProductCardForm
    template_name = 'product_card/edit_pc.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation_name'] = 'Create'
        return context


class UpdateProductCard(generic.UpdateView):
    model = models.Book
    form_class = forms.ProductCardForm
    template_name = 'product_card/edit_pc.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation_name'] = 'Update'
        return context


class DeleteProductCard(generic.DeleteView):
    model = models.Book
    template_name = 'product_card/delete_pc.html'

    def get_success_url(self):
        return reverse_lazy('product_card:pc_list')
    

class SearchResultView(generic.View):
    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('q')
        results = ''
        if query:
            results = models.Book.objects.filter(
                Q(author__name__icontains=query) | Q(name__icontains=query) | Q(author__surname__icontains=query)
            ).distinct()
        paginator = Paginator(results, 12)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'product_card/search.html', context={
            'title': 'Search',
            'results': page_obj,
            'count': paginator.count,
        })

class BookDetail(generic.DetailView):
    def get(self, request, *args, **kwargs):
        book = get_object_or_404(models.Book, pk=kwargs['pk'])
        return render(request, 'product_card/book_detail.html', context={
            'book': book,
        }) 
    

class CatalogView(generic.View):
    def get(self, request, *args, **kwargs):
        book = models.Book.objects.all()
        paginator = Paginator(book, 12)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(
            request,
            'product_card/catalog.html',
            context={
                'page_obj': page_obj
            }
        )
    

class PortalView(generic.TemplateView):
    def get(self, request, *args, **kwargs):
        return render(
            request, 'product_card/portal_detail.html'
        )

src/product_card/templates/product_card/book_detail.html
{% extends "base.html" %}

{% block title %}
{{ object.name }}
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h2>{{ book.name }}</h2>
    </div>
</div>
<div class="shadow p-3 mb-5 bg-body rounded">
    <hr class="featurette-divider">
    <div class="row featurette">
        <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading fw-normal lh-1">{{ book.name }}</h2><br>
        <h4 class="featurette-heading fw-normal lh-1" >Author:<span class="text-muted"><em> {% for author in book.author.all %}{{ author }} {% if not forloop.last %}, {% endif %} {% endfor %}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Pages:<span class="text-muted"><em> {{ book.pages }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Binding:<span class="text-muted"><em> {{ book.binding }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Format:<span class="text-muted"><em> {{ book.format }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >ISBN:<span class="text-muted"><em> {{ book.isbn }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Weight:<span class="text-muted"><em> {{ book.weight }} gr</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Publishing year:<span class="text-muted"><em> {{ book.publishing_year }}</h4></em>
        <h4 class="featurette-heading fw-normal lh-1" >Age restriction:<span class="text-muted"><em> {{ book.age_restriction }}</h4></em>
       
        <br>
        <h5 class="featurette-heading fw-normal lh-1" ><span class="text-muted"> {{ book.description }}</h5>
      </div>
      <div class="col-md-5 order-md-1">
 
        <img src="{% if book.image %}{{ book.image.url }}{% else %}{% endif %}" alt="Default image" width="500" height="500" border="1" >

      </div>
    </div>
    <h6 class="featurette-heading fw-normal lh-1" >Changed:<span class="text-muted"><em> {{ book.modification_date }}</h6></em><br>
    <hr>
    <a href="" onclick="history.go(-1); return false;" class="btn btn-secondary">Cancel</i></a>
  </div>
{% endblock content %}

src/product_card/templates/product_card/catalog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'bs/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'bs/js/bootstrap.min.js' %}"></script>
    <link href="{% static 'bs/css/custom.css' %}" rel="stylesheet">
    <title>{% block title%}Book service{% endblock title %}</title>
</head>
<body class="d-flex flex-column h-100 text-bg-light">
    <div class="container">
        <header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">BOOK SERVICE</a><br>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'product_card:service_navigation' %}">Navigation</a>
          </li>

        
        <form action="{% url 'search_results' %}" method="get" class="d-flex" role="search">
          <input name="q" type="text" class="form-control me-2" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success me-4" type="submit">Search</button>
        </form>
</header>

<main>

<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">A room without books is like a body without a soul.</h1>
      <p class="lead text-muted"> © Cicéron</p>
    </div>
  </div>
</section>

<div class="album py-5 bg-light">
  <div class="container size-fixed">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for obj in page_obj %}
      <div class="col">
        <div class="card shadow-sm">
          <img src="{% if obj.image %}{{ obj.image.url }}{% else %}{% endif %}" alt="Default image" border="1" width="100%" height="500" >
          <div class="card-body">
            <p class="card-text">{{ obj.description }}</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{% url 'product_card:book_detail' pk=obj.pk %}"  type="submit" class="btn btn-sm btn-outline-secondary">View</a>

                <a href="{% url 'product_card:pc_update' pk=obj.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>

              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
</main>


<footer class="py-3 my-4">
  <div class="shadow p-3 mb-5 bg-body rounded">
  <div class="container">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      </ul>
    <p class="text-center text-muted">&copy; 2023 LeatherDiamond</p>
  </div>
  </div>
</footer>
</main>
</body>
</html>

src/product_card/templates/product_card/delete_pc.html
{% extends "base.html" %}

{% block title %}
Delete the book
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
<div class="text-center">
    <h1>Are you sure that you want to delete the book?</h1><br>
</div>
</div>
    <p>Book <b>"{{ object.name }}"</b> will be permanently deleted from the list.<br>
    If you are agree please click delete button.</p><br>
    <form action="" method="post">
        {% csrf_token %}
        <a href="{% url 'product_card:pc_list' %}" class="btn btn-secondary">Cancel</i></a>
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
{% endblock content %}

src/product_card/templates/product_card/detail_pc.html
{% extends "base.html" %}

{% block title %}
Book preview
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
<div class="text-center">
    <h1><span style="color: green;">Book successfully created!</span></h1>
</div>
</div>
    Card name: <b>"{{ object.name }}"</b><br>
    <br>
    <td><a href="{% url 'product_card:pc_create' %}" class="btn btn-outline-success mb-3">Create a new book</a></td>
    <br>
    <td><a href="{% url 'product_card:pc_list' %}" class="btn btn-outline-success mb-3">Show the list of books</a></td>
{% endblock content %}

src/product_card/templates/product_card/edit_pc.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
{{ operation_name }} the book
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
<div class="text-center">
    <h1>{{ operation_name }} the book</h1>
</div>
</div>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <a href="{% url 'product_card:pc_list' %}" onclick="history.go(-1); return false;" class="btn btn-secondary">Cancel</i></a>
        <input type="submit" value="Save changes" class="btn btn-success">
    </form>
{% endblock content %}

src/product_card/templates/product_card/list_pc.html
{% extends "base.html" %}

{% block title %}
List of books
{% endblock title %}

{% block content %}
    <div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h1>List of books</h1>
    </div>
    </div>
        <td><a href="{% url 'product_card:pc_create' %}" class="btn btn-outline-success mb-3">Create a new book</a></td>
        <div class="shadow p-3 mb-5 bg-body rounded">
        <div class="table-responsive">
        <div class="text-center">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                  <th scope="col">Book name</th>
                  <th scope="col">Author</th>
                  <th scope="col">ISBN</th>
                  <th scope="col">Modified</th>
                  <th scope="col">Options</th>
                </tr>
              </thead>
            <tbody>
        {% for obj in object_list %}
        <tr>
            <td>{{ obj.name }}</td>
            <td>
            {% for author in obj.author.all %}
            {{ author.name }} {{author.surname}}
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
            </td>
            <td>{{ obj.isbn }}</td>
            <td>{{ obj.modification_date }}</td>
            <td><a href="{% url 'product_card:pc_update' pk=obj.pk %}" class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i></a>
                <a href="{% url 'product_card:pc_delete' pk=obj.pk %}" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#id{{obj.pk}}"><i class="bi bi-x-lg"></i></a></td>
        </tr>
                <!-- Modal -->
<div class="modal fade" id="id{{obj.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Are you sure that you want to delete the book?</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            Book <b>"{{ obj.name }}"</b> will be permanently deleted from the list.
            If you are agree please click delete button.<br>
            <br>
            <form action="{% url 'product_card:pc_delete' pk=obj.pk %}" method="post">
                {% csrf_token %}
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <input type="submit" value="Delete" class="btn btn-danger">
            </form>
        </div>
        </div>
      </div>
    </div>
  </div>
            </tbody>
        </div>
        {% endfor %}
        </table>
        
{% endblock content %}

src/product_card/templates/product_card/portal_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Service navigation
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h2>Welcome to navigation panel!</h2>
    </div>
</div>

<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
            <i class="bi bi-1-circle"> <strong>List of authors.</strong></i> 
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
            Here you can see the list of authors and update/create/delete author incstance.<br>
            <strong>Click the button to start.</strong><br>
            <br>
            <a href="{%url 'references:authors_list'%}" class="btn btn-outline-success mb-3">Show the list of authors</a>
          </div>
      </div>
    </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
    <i class="bi bi-2-circle"> <strong>List of books.</strong></i>
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
      <div class="accordion-body">
          Find the list of books after clicking the button. You also can update/create/delete book instance in a few steps after clicking the button.<br>
          <strong>Click the button to start.</strong><br>
          <br>
          <a href="{%url 'product_card:pc_list'%}" class="btn btn-outline-success mb-3">Show the list of books</a>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
    <i class="bi bi-3-circle"> <strong>New book.</strong></i>
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
      <div class="accordion-body">
          Create a new book directly.<br>
          <strong>Just click the button to start.</strong><br>
          <br>
          <a href="{%url 'product_card:pc_create'%}" class="btn btn-outline-success mb-3">Create a new book</a>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingFour">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
    <i class="bi bi-4-circle"> <strong>New author.</strong></i>
      </button>
    </h2>
    <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
      <div class="accordion-body">
          Create a new author directly.<br>
          <strong>Just click the button to start.</strong><br>
          <br>
          <a href="{%url 'references:author_create'%}" class="btn btn-outline-success mb-3">Create a new author</a>
      </div>
    </div>
  </div>
{% endblock content %}

src/product_card/templates/product_card/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Search{% endblock %}



{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">

            <p class="lead">Results found: {{ count }}</p>
            {% for result in results %}
                <a href="{% url 'product_card:book_detail' pk=result.pk %}"><h2>{{ result.name }}</h2></a>
                Author: {% for author in result.author.all %}{{ author }} {% endfor %}<br>
                Description: {{ result.description|safe }}
                <hr>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block pagination %}
    <nav aria-label="Paginate me">
      <ul class="pagination justify-content-center">
        {% if results.has_previous %}
          <a class="page-link" href="?page={{ results.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" tabindex="-1">Previous</a>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link disabled" href="#" tabindex="-1">Previous</a>
        </li>
        {% endif %}
        {% for i in results.paginator.page_range %}
        {% if i == results.number %}
          <li class="page-item active"><a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if results.has_next %}
          <a class="page-link" href="?page={{ results.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Next</a>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#">Next</a>
          </li>
        {% endif %}
      </ul>
    </nav>
    <br>
{% endblock %}