src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from product_card.views import SearchResultView, CatalogView


urlpatterns = [
    path("admin/", admin.site.urls),
    path('references/', include('references.urls', namespace="references")),
    path('product_card/', include('product_card.urls', namespace="product_card")),
    path('search/', SearchResultView.as_view(), name='search_results'),
    path('', CatalogView.as_view(), name='catalog'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/references/urls.py
from django.urls import path
from . import views

app_name = "references"
urlpatterns = [

    #Authors URLs

    path('author_preview/<int:pk>/', views.ShowAuthor.as_view(), name='author_detail'),
    path('author_create/', views.CreateAuthor.as_view(), name='author_create'),
    path('author_update/<int:pk>/', views.UpdateAuthor.as_view(), name='author_update'),
    path('author_delete/<int:pk>/', views.DeleteAuthor.as_view(), name='author_delete'),
    path('authors_list/', views.ShowAuthors.as_view(), name='authors_list'),
]

src/product_card/models.py
from django.db import models
from references.models import BookAuthor
from django.urls import reverse_lazy
from django.utils.datetime_safe import date
from django.core.exceptions import ValidationError

# Create your models here.

class Book(models.Model):
    name = models.CharField(
       max_length=70,
       verbose_name="Book name"
    )
    image = models.ImageField(
        verbose_name="Book image",
        upload_to='uploads/%Y/%m/%d/',
        blank=True,
        null=True
    )
    author = models.ManyToManyField(
        BookAuthor,
    )
    publishing_year=models.CharField(
        max_length=11,
        verbose_name="Publishing year"
    )
    pages = models.IntegerField(
        verbose_name="Pages"
    )
    binding = models.CharField(
        max_length=15,
        verbose_name="Binding"
    )
    format = models.CharField(
        max_length=7,
        verbose_name="Format"
    )
    isbn = models.CharField(
        max_length=30,
        verbose_name="ISBN"
    )
    weight = models.IntegerField(
        verbose_name="Weight",
        help_text="Weight in grams"
    )
    age_restriction = models.IntegerField( 
        verbose_name="Age restriction"
    )
    date_of_addition = models.DateField(
        verbose_name="Date of addition"
    )
    modification_date = models.DateTimeField(
        auto_now=True,
        verbose_name="Modification date"
    )
    description = models.TextField(
        blank = True,
        null = True
    )
    

    def get_absolute_url(self):
        return reverse_lazy('product_card:pc_detail', kwargs={'pk': self.pk})

    def clean(self):
        if str(self.date_of_addition) > str(date.today()):
            raise ValidationError({'date_of_addition': 'Must not be later than today!'})

    def __str__(self):
        return str(self.name)

src/references/models.py
from django.db import models
from django.urls import reverse_lazy

# Create your models here.

class BookAuthor(models.Model):
    name = models.CharField(
       max_length=30,
       verbose_name="Author's name",
    )
    surname = models.CharField(
       max_length=30,
       verbose_name="Author's surname",
    )
    description = models.TextField(
        blank=True,
        null=True
    )
      
    def get_absolute_url(self):
        return reverse_lazy('references:author_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name + ' ' + self.surname


    

src/references/forms.py
from django import forms
from . import models
from product_card import models

#Forms for references

class AuthorForm(forms.ModelForm):
    related_books = forms.ModelMultipleChoiceField(
        queryset=models.Book.objects.none(),
        widget=forms.CheckboxSelectMultiple(attrs={"checked":""}),
        disabled=True,
        required=False
    )
    
    class Meta:
        model = models.BookAuthor
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.pk:
            self.fields['related_books'].queryset = models.Book.objects.filter(author=self.instance)
            self.fields['related_books'].initial = self.instance.book_set.all()

    def save(self, commit=True):
        author = super().save(commit=False)
        if commit:
            author.save()
            self.save_m2m()
        return author

src/references/views.py
from django.shortcuts import render
from django.views import generic
from references import models, forms
from django.urls import reverse_lazy

# Create your views here.


#CBV for Author model.

class ShowAuthors(generic.ListView):
    model = models.BookAuthor
    template_name = 'references/list_author.html'


class ShowAuthor(generic.DetailView):
    model = models.BookAuthor
    template_name = 'references/detail_author.html'


class CreateAuthor(generic.CreateView):
    model = models.BookAuthor
    form_class = forms.AuthorForm
    template_name = 'references/edit_author.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation_name'] = 'Create'
        return context


class UpdateAuthor(generic.UpdateView):
    model = models.BookAuthor
    form_class = forms.AuthorForm
    template_name = 'references/edit_author.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['operation_name'] = 'Update'
        return context


class DeleteAuthor(generic.DeleteView):
    model = models.BookAuthor
    template_name = 'references/delete_author.html'

    def get_success_url(self):
        return reverse_lazy('references:authors_list')

src/references/templates/references/delete_author.html
{% extends "base.html" %}

{% block title %}
Delete author
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
<div class="text-center">
    <h1>Are you sure that you want to delete the author?</h1><br>
</div>
</div>
<p>Author <b>"{{ object.name }} {{ object.surname}}"</b> will be permanently deleted from the list.<br>
    If you are agree please click delete button.</p><br>
    Description: {{ object.description|default:"No description was provided" }}<br>
    <br>
    <form action="" method="post">
        {% csrf_token %}
        <a href="{% url 'references:authors_list' %}" class="btn btn-secondary">Cancel</i></a>
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
{% endblock content %}

src/references/templates/references/detail_author.html
{% extends "base.html" %}

{% block title %}
Author's preview
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h1><span style="color: green;">Author successfully created!</span></h1>
    </div>
    </div>
    Author's data: <b>"{{ object.name }} {{object.surname}}"</b><br>
    Description: {{ object.description|default:"No description was provided" }}<br>
    <br>
    <td><a href="{% url 'references:author_create' %}" class="btn btn-outline-success mb-3">Create a new author</a></td>
    <br>
    <td><a href="{% url 'references:authors_list' %}" class="btn btn-outline-success mb-3">Show the list of authors</a></td>
{% endblock content %}

src/references/templates/references/edit_author.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
{{ operation_name }} author
{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
<div class="text-center">
    <h1>{{ operation_name }} book's author</h1>
</div>
</div>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <a href="{% url 'references:authors_list' %}" class="btn btn-secondary">Cancel</i></a>
        <input type="submit" value="Save changes" class="btn btn-success">
    </form>
{% endblock content %}

src/references/templates/references/list_author.html
{% extends "base.html" %}

{% block title %}List of authors{% endblock title %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <div class="text-center">
        <h1>List of authors</h1>
    </div>
    </div>
        <td><a href="{% url 'references:author_create' %}" class="btn btn-outline-success mb-3">Create a new author</a></td>
        <div class="shadow p-3 mb-5 bg-body rounded">
        <div class="table-responsive">
        <div class="text-center">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                  <th scope="col">Authors data</th>
                  <th scope="col">Related books</th>
                  <th scope="col">Description</th>
                  <th scope="col">Options</th>
                </tr>
              </thead>
            <tbody>
        {% for obj in object_list %}
        <tr>
            <td>{{ obj.name }} {{ obj.surname }}</td>
            <td>
              {% for book in obj.book_set.all %}
              {{ book.name }}
              {% if not forloop.last %}, {% endif %}
              {% endfor %}
            </td>
            <td>{{ obj.description }}</td>
            <td><a href="{% url 'references:author_update' pk=obj.pk %}" class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i></a>
                <a href="{% url 'references:author_delete' pk=obj.pk %}" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#id{{obj.pk}}"><i class="bi bi-x-lg"></i></a></td>
        </tr>
                <!-- Modal -->
<div class="modal fade" id="id{{obj.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Are you sure that you want to delete the author?</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            Author <b>"{{ obj.name }} {{ obj.surname }}"</b> will be permanently deleted from the list.
            If you are agree please click delete button.<br>
            <br>
            <form action="{% url 'references:author_delete' pk=obj.pk %}" method="post">
                {% csrf_token %}
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <input type="submit" value="Delete" class="btn btn-danger">
            </form>
        </div>
        </div>
      </div>
    </div>
  </div>
            </tbody>
        </div>
        {% endfor %}
        </table>
{% endblock content %}